{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# CogPonder: N-Back Task with Fixed Hyper-parameters\n",
    "\n",
    "This notebook trains a single-task CogPonder agent on N-back task. The operator is a spatiotemporal encoder (CNN+LSTM) with fixed hyper-parameters and a binary classification head.\n",
    "\n",
    "## Data\n",
    "\n",
    "Here, we only use the 2-back data from the *Self-Regulation Ontology* dataset ([see `data/Self_Regulation_Ontology/`](../data/Self_Regulation_Ontology/README.md)).\n",
    "\n",
    "#### 2-back\n",
    "\n",
    "The input includes recent N+1 symbols, including the one presented in the current trial; the last input is the current symbol. The output is the response to the current trial (either match or non-match).\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "notebookRunGroups": {
     "groupValue": "1"
    }
   },
   "outputs": [],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 3\n",
    "\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from IPython.display import display, clear_output\n",
    "\n",
    "import torch\n",
    "import pytorch_lightning as pl\n",
    "import pandas as pd\n",
    "from pytorch_lightning.callbacks import EarlyStopping\n",
    "from src.cogponder import CogPonderModel\n",
    "from src.cogponder.data import NBackSRODataset, CogPonderDataModule\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "notebookRunGroups": {
     "groupValue": "1"
    },
    "tags": [
     "parameters"
    ]
   },
   "outputs": [],
   "source": [
    "# Parameters\n",
    "\n",
    "# number of maximum epochs to train (early stopping will be applied)\n",
    "# early stopping patience is 10% of max_epochs (min 10 epochs)\n",
    "max_epochs = 2000\n",
    "batch_size = 1024\n",
    "step_duration = 10\n",
    "n_subjects = 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading N-back dataset... Done!\n"
     ]
    }
   ],
   "source": [
    "# Data\n",
    "\n",
    "print(f'Loading N-back dataset... ', end='')\n",
    "\n",
    "dataset = NBackSRODataset(n_subjects=n_subjects,\n",
    "                          n_back=2,\n",
    "                          step_duration=step_duration)\n",
    "\n",
    "datamodule = CogPonderDataModule(dataset, batch_size=batch_size, num_workers=8)\n",
    "datamodule.prepare_data()\n",
    "# determine some parameters from data\n",
    "n_subjects = torch.unique(dataset[:][0]).size(0)\n",
    "n_contexts = torch.unique(dataset[:][2]).size(0)\n",
    "n_features = dataset[:][3].size(-1)\n",
    "n_outputs = torch.unique(dataset[:][4]).size(0)\n",
    "max_response_step = dataset[:][5].max().int().item() + 1\n",
    "\n",
    "configs = {\n",
    "    'inputs_dim': n_features,\n",
    "    'outputs_dim': n_outputs,\n",
    "    'embeddings_dim': 8,\n",
    "    'time_loss_beta': 10.,\n",
    "    'learning_rate': 1e-2,\n",
    "    'max_response_step': max_response_step,\n",
    "    'n_contexts': n_contexts,\n",
    "    'n_subjects': n_subjects,\n",
    "    'subject_embeddings_dim': 2,\n",
    "    'task': 'nback',\n",
    "    'operator_type': 'spatiotemporal'\n",
    "}\n",
    "\n",
    "print('Done!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "GPU available: False, used: False\n",
      "TPU available: False, using: 0 TPU cores\n",
      "IPU available: False, using: 0 IPUs\n",
      "HPU available: False, using: 0 HPUs\n",
      "Restoring states from the checkpoint path at models/checkpoints/nback/cogponder_5subjects_991epochs.ckpt\n",
      "/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:337: UserWarning: The dirpath has changed from '/workspaces/CogPonder/lightning_logs/version_15/checkpoints' to '/workspaces/CogPonder/lightning_logs/version_16/checkpoints', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.\n",
      "  warnings.warn(\n",
      "\n",
      "  | Name          | Type                         | Params\n",
      "---------------------------------------------------------------\n",
      "0 | halt_node     | HaltingModule                | 81    \n",
      "1 | iterator_node | IteratorModule               | 322   \n",
      "2 | operator_node | SpatioTemporalOperatorModule | 371   \n",
      "3 | embeddings    | Embedding                    | 40    \n",
      "4 | context_node  | Sequential                   | 90    \n",
      "5 | resp_loss_fn  | ResponseLoss                 | 0     \n",
      "6 | time_loss_fn  | ResponseTimeLoss             | 0     \n",
      "---------------------------------------------------------------\n",
      "904       Trainable params\n",
      "0         Non-trainable params\n",
      "904       Total params\n",
      "0.004     Total estimated model params size (MB)\n",
      "Restored all states from the checkpoint at models/checkpoints/nback/cogponder_5subjects_991epochs.ckpt\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5e887241b00547bea5b59c2a0185b07d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Training: 0it [00:00, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).\n",
      "\u0000"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_2072/2918853829.py\", line 22, in <module>\n",
      "    trainer.fit(model,\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py\", line 532, in fit\n",
      "    call._call_and_handle_interrupt(\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py\", line 43, in _call_and_handle_interrupt\n",
      "    return trainer_fn(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py\", line 571, in _fit_impl\n",
      "    self._run(model, ckpt_path=ckpt_path)\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py\", line 980, in _run\n",
      "    results = self._run_stage()\n",
      "              ^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py\", line 1023, in _run_stage\n",
      "    self.fit_loop.run()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py\", line 202, in run\n",
      "    self.advance()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py\", line 355, in advance\n",
      "    self.epoch_loop.run(self._data_fetcher)\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py\", line 134, in run\n",
      "    self.on_advance_end()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py\", line 249, in on_advance_end\n",
      "    self.val_loop.run()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/utilities.py\", line 181, in _decorator\n",
      "    return loop_run(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py\", line 101, in run\n",
      "    self.reset()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/evaluation_loop.py\", line 217, in reset\n",
      "    iter(data_fetcher)  # creates the iterator inside the fetcher\n",
      "    ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/fetchers.py\", line 105, in __iter__\n",
      "    super().__iter__()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/loops/fetchers.py\", line 54, in __iter__\n",
      "    self.dataloader_iter = iter(self.dataloader)\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py\", line 293, in __iter__\n",
      "    iter(iterator)\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py\", line 136, in __iter__\n",
      "    self._load_current_iterator()\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pytorch_lightning/utilities/combined_loader.py\", line 147, in _load_current_iterator\n",
      "    self.iterators = [iter(self.iterables[self._iterator_idx])]\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/torch/utils/data/dataloader.py\", line 441, in __iter__\n",
      "    return self._get_iterator()\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/torch/utils/data/dataloader.py\", line 388, in _get_iterator\n",
      "    return _MultiProcessingDataLoaderIter(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/torch/utils/data/dataloader.py\", line 1024, in __init__\n",
      "    index_queue = multiprocessing_context.Queue()  # type: ignore[var-annotated]\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/multiprocessing/context.py\", line 103, in Queue\n",
      "    return Queue(maxsize, ctx=self.get_context())\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/multiprocessing/queues.py\", line 43, in __init__\n",
      "    self._rlock = ctx.Lock()\n",
      "                  ^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/multiprocessing/context.py\", line 68, in Lock\n",
      "    return Lock(ctx=self.get_context())\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/multiprocessing/synchronize.py\", line 162, in __init__\n",
      "    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/multiprocessing/synchronize.py\", line 57, in __init__\n",
      "    sl = self._semlock = _multiprocessing.SemLock(\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: [Errno 28] No space left on device\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 568, in _process_state\n",
      "    rex = cls._process_regex(tdef[0], rflags, state)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 496, in _process_regex\n",
      "    regex = regex.get()\n",
      "            ^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 484, in get\n",
      "    return regex_opt(self.words, prefix=self.prefix, suffix=self.suffix)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 91, in regex_opt\n",
      "    return prefix + regex_opt_inner(strings, '(') + suffix\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in regex_opt_inner\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in <genexpr>\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in regex_opt_inner\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in <genexpr>\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in regex_opt_inner\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in <genexpr>\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in regex_opt_inner\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in <genexpr>\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in regex_opt_inner\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/regexopt.py\", line 77, in <genexpr>\n",
      "    '|'.join(regex_opt_inner(list(group[1]), '')\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/torch/utils/data/_utils/signal_handling.py\", line 66, in handler\n",
      "    _error_if_any_worker_fails()\n",
      "RuntimeError: DataLoader worker (pid 164150) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1428, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1319, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1172, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1087, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 968, in format_record\n",
      "    _format_traceback_lines(\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 215, in _format_traceback_lines\n",
      "    line = stack_line.render(pygmented=has_colors).rstrip('\\n') + '\\n'\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/stack_data/core.py\", line 391, in render\n",
      "    start_line, lines = self.frame_info._pygmented_scope_lines\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/stack_data/core.py\", line 824, in _pygmented_scope_lines\n",
      "    lines = _pygmented_with_ranges(formatter, code, ranges)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/stack_data/utils.py\", line 163, in _pygmented_with_ranges\n",
      "    lexer = MyLexer(stripnl=False)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 650, in __call__\n",
      "    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 589, in process_tokendef\n",
      "    cls._process_state(tokendefs, processed, state)\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 552, in _process_state\n",
      "    tokens.extend(cls._process_state(unprocessed, processed,\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 552, in _process_state\n",
      "    tokens.extend(cls._process_state(unprocessed, processed,\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/conda/envs/cogponder/lib/python3.11/site-packages/pygments/lexer.py\", line 570, in _process_state\n",
      "    raise ValueError(\"uncompilable regex %r in state %r of %r: %s\" %\n",
      "ValueError: uncompilable regex <pygments.lexer.words object at 0x7f8b7243f450> in state 'builtins' of <class 'stack_data.utils._pygmented_with_ranges.<locals>.MyLexer'>: DataLoader worker (pid 164150) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.\n"
     ]
    }
   ],
   "source": [
    "# Experiment\n",
    "\n",
    "model = CogPonderModel(**configs)\n",
    "\n",
    "# model = torch.compile(model)\n",
    "\n",
    "# Trainer\n",
    "trainer = pl.Trainer(\n",
    "    max_epochs=max_epochs,\n",
    "    min_epochs=200,\n",
    "    accelerator='cpu',\n",
    "    log_every_n_steps=1,\n",
    "    # overfit_batches=True,\n",
    "    # accumulate_grad_batches=2,\n",
    "    callbacks=[\n",
    "        # EarlyStopping(monitor='val/total_loss',\n",
    "        #               patience=100,\n",
    "        #               mode='min', min_delta=0.001),\n",
    "    ])\n",
    "\n",
    "# Fit and evaluate the model\n",
    "trainer.fit(model,\n",
    "            ckpt_path='models/checkpoints/nback/cogponder_5subjects_991epochs.ckpt',\n",
    "            datamodule=datamodule)\n",
    "\n",
    "# save checkpoint\n",
    "ckpt_path = f'models/checkpoints/nback/cogponder_{n_subjects}subjects_{trainer.current_epoch}epochs.ckpt'\n",
    "trainer.save_checkpoint(ckpt_path)\n",
    "\n",
    "clear_output()\n",
    "\n",
    "print('Saved checkpoint to:', ckpt_path)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "de6d99ee160217cabdbdc9334fcf26c57070993174a3cfee67906e3b48dd785a"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
